#! /bin/sh
#
# Copyright (c) 2010-2017 @ Quectel Wireless Solutions Co., Ltd.  All Rights Reserved.
#
# start_z_oemapp_le  init.d script to mount oemapp and start the customer application.

DAEMON=/usr/bin/ql_softsim

set -e

case "$1" in
    start)
        echo -n "Starting ql-softsim: "
        start-stop-daemon -S -b -x $DAEMON
        echo "done"
        ;;
    stop)
        echo -n "Stopping ql-softsim: "
        tart-stop-daemon -K -x $DAEMON
        echo "done"
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage $0 { start | stop | restart}" >&2
        exit 1
        ;;
esac

exit 0
