#
# Makefile for quectel rawdata drivers.
#
obj-$(CONFIG_QRAWDATA)		+= quec_raw_data_item.o
obj-$(CONFIG_QRAWDATA)		+= quec_raw_flash_data.o
obj-$(CONFIG_QRAWDATA)		+= quec_flash.o
obj-$(CONFIG_QRAWDATA)		+= quec_crc.o