# Make bootimage. it's auto-generated by linux-quic.bbapend.
export KERNEL_CMD_PARAMS="noinitrd ro console=ttyHSL0,115200,n8 androidboot.hardware=qcom ehci-hcd.park=3 msm_rtb.filter=0x37 lpm_levels.sleep_disabled=1 earlycon=msm_hsl_uart,0x78b3000"
export PAGE_SIZE="4096"
export KERNEL_BASE="0x80000000"
export MKUBIFS_ARGS="-m 4096 -e 253952 -c 2146 -F "
export UBINIZE_ARGS="-m 4096 -p 256KiB -s 4096"
export KERNEL_TAGS_OFFSET=0x81E00000
