#ifndef QL_MANAGER_ACCESS_MSGR_BT_SERVICE_01_H
#define QL_MANAGER_ACCESS_MSGR_BT_SERVICE_01_H
/**
  @file ql_manager_access_msgr_bt_v01.h

  @brief This is the public header file which defines the ql_manager_access_msgr_bt service Data structures.

  This header file defines the types and structures that were defined in
  ql_manager_access_msgr_bt. It contains the constant values defined, enums, structures,
  messages, and service message IDs (in that order) Structures that were
  defined in the IDL as messages contain mandatory elements, optional
  elements, a combination of mandatory and optional elements (mandatory
  always come before optionals in the structure), or nothing (null message)

  An optional element in a message is preceded by a uint8_t value that must be
  set to true if the element is going to be included. When decoding a received
  message, the uint8_t values will be set to true or false by the decode
  routine, and should be checked before accessing the values that they
  correspond to.

  Variable sized arrays are defined as static sized arrays with an unsigned
  integer (32 bit) preceding it that must be set to the number of elements
  in the array that are valid. For Example:

  uint32_t test_opaque_len;
  uint8_t test_opaque[16];

  If only 4 elements are added to test_opaque[] then test_opaque_len must be
  set to 4 before sending the message.  When decoding, the _len value is set
  by the decode routine and should be checked so that the correct number of
  elements in the array will be accessed.

*/
/*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*
  

  
 *====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*/
/*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*
 *THIS IS AN AUTO GENERATED FILE. DO NOT ALTER IN ANY WAY
 *====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*/

/* This file was generated with Tool version 6.14.7 
   It was generated on: Mon Dec 15 2025 (Spin 0)
   From IDL File: ql_manager_access_msgr_bt_v01.idl */

/** @defgroup ql_manager_access_msgr_bt_qmi_consts Constant values defined in the IDL */
/** @defgroup ql_manager_access_msgr_bt_qmi_msg_ids Constant values for QMI message IDs */
/** @defgroup ql_manager_access_msgr_bt_qmi_enums Enumerated types used in QMI messages */
/** @defgroup ql_manager_access_msgr_bt_qmi_messages Structures sent as QMI messages */
/** @defgroup ql_manager_access_msgr_bt_qmi_aggregates Aggregate types used in QMI messages */
/** @defgroup ql_manager_access_msgr_bt_qmi_accessor Accessor for QMI service object */
/** @defgroup ql_manager_access_msgr_bt_qmi_version Constant values for versioning information */

#include <stdint.h>
#include "qmi_idl_lib.h"
#include "ql_manager_access_msgr_common_v01.h"


#ifdef __cplusplus
extern "C" {
#endif

/** @addtogroup ql_manager_access_msgr_bt_qmi_version
    @{
  */
/** Major Version Number of the IDL used to generate this file */
#define QL_MANAGER_ACCESS_MSGR_BT_V01_IDL_MAJOR_VERS 0x01
/** Revision Number of the IDL used to generate this file */
#define QL_MANAGER_ACCESS_MSGR_BT_V01_IDL_MINOR_VERS 0x01
/** Major Version Number of the qmi_idl_compiler used to generate this file */
#define QL_MANAGER_ACCESS_MSGR_BT_V01_IDL_TOOL_VERS 0x06

/**
    @}
  */

/** @addtogroup ql_manager_access_msgr_bt_qmi_messages
    @{
  */
/**  Message;  */
typedef struct {

  /* Mandatory */
  uint8_t bt_addr[6];
}ql_manager_msgr_set_bt_addr_req_msg_v01;  /* Message */
/**
    @}
  */

/** @addtogroup ql_manager_access_msgr_bt_qmi_messages
    @{
  */
/**  Message;  */
typedef struct {

  /* Mandatory */
  result_v01 res;
}ql_manager_msgr_set_bt_addr_resp_msg_v01;  /* Message */
/**
    @}
  */

/** @addtogroup ql_manager_access_msgr_bt_qmi_messages
    @{
  */
/**  Message;  */
typedef struct {
  /* This element is a placeholder to prevent the declaration of
     an empty struct.  DO NOT USE THIS FIELD UNDER ANY CIRCUMSTANCE */
  char __placeholder;
}ql_manager_msgr_get_bt_addr_req_msg_v01;

  /* Message */
/**
    @}
  */

/** @addtogroup ql_manager_access_msgr_bt_qmi_messages
    @{
  */
/**  Message;  */
typedef struct {

  /* Mandatory */
  result_v01 res;

  /* Mandatory */
  uint8_t bt_addr[6];
}ql_manager_msgr_get_bt_addr_resp_msg_v01;  /* Message */
/**
    @}
  */

/* Conditional compilation tags for message removal */ 

/*Extern Definition of Type Table Object*/
/*THIS IS AN INTERNAL OBJECT AND SHOULD ONLY*/
/*BE ACCESSED BY AUTOGENERATED FILES*/
extern const qmi_idl_type_table_object ql_manager_access_msgr_bt_qmi_idl_type_table_object_v01;


#ifdef __cplusplus
}
#endif
#endif

