#! /bin/sh
#
# ql_beacon init.d script: periodically sends device-info beacons to the
# Intellicar telemetry server.

set -e

case "$1" in
  start)
        echo -n "Starting ql_beacon: "
        start-stop-daemon -S -b -a ql_beacon
        echo "done"
        ;;
  stop)
        echo -n "Stopping ql_beacon: "
        start-stop-daemon -K -n ql_beacon
        echo "done"
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage start_ql_beacon_le { start | stop | restart}" >&2
        exit 1
        ;;
esac

exit 0
