#
# Makefile for the quectel drivers.
#
# 1 Jan 2018, Gale
# 

obj-$(CONFIG_QL_LPM)	+= ql_lpm/
obj-$(CONFIG_QSMD)	+= qsmd/
obj-$(CONFIG_QSMEM)	+= qsmem/
obj-$(CONFIG_QSTART)	+= qstart/
obj-$(CONFIG_QTZONE)	+= qtzone/
obj-$(CONFIG_QRAWDATA)	+= rawdata/
obj-$(CONFIG_QFASTSHUTDOWN)	+= qfastshutdown/
obj-$(CONFIG_QTEE)	+= qtee/
