#! /bin/sh

set -e

tts_prop=`cat /usr/share/TTS/tts.prop`

case "$1" in
start)
    # add by quectel 2016.06.26  end	
    echo -n "Starting quectel-tts-service "
    #charles-20190312 create dir /data/tts
    if [ ! -d /data/tts ]
    then
        mkdir /data/tts
    fi

    if [ ! -f /data/tts/libql_tts.so.1 ]
    then
        if [ "$tts_prop" = "TTS_LANG=ch" ]
        then
            ln -sf /usr/lib/libql_tts_ch.so.1 /data/tts/libql_tts.so.1
        elif [ "$tts_prop" = "TTS_LANG=eng" ]
        then
            ln -sf /usr/lib/libql_tts_eng.so.1 /data/tts/libql_tts.so.1
        else
            ln -sf /usr/lib/libql_tts_ch.so.1 /data/tts/libql_tts.so.1   
        fi
    fi
    sync
    start-stop-daemon -S -b -a /usr/bin/quectel_tts_service
    echo "done"
    ;;
  stop)
    echo -n "Stopping atreset: "
    start-stop-daemon -K -n quectel_tts_service
    echo "done"
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage quectel_tts_service{ start | stop | restart }" >&2
    exit 1
    ;;
esac

exit 0
